""" defining the constants for the system business rules """
AUCTION_FEE_FRACTION = 0.1
AUCTION_FEE_FRACTION_FIRST_PLACE = 0.03
AUCTION_FEE_FRACTION_SECOND_PLACE = 0.05
AUCTION_FEE_FRACTION_THIRD_PLACE = 0.07
SHIPMENT_FEE_FRACTION = 0.1
AUTHENTICATION_FEE_FRACTION = 0.1
AUTHENTICATION_FAILED_FRACTION = 1
